db:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=mypassword
  expose:
    - "3306"    
  ports:
    - "3333:3306"

goserver3:
  build: ./go-app
  working_dir: /go/src/go-app
  links:
    - db
  command: go run main.go
  volumes:
    - ./go-app:/go/src/go-app
  ports:
    - "8888:8080"

nodeserver3:
  build: ./node-app
  links:
    - db
  ports:
    - "8887:8080"